// <auto-generated />
namespace PMS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V00 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V00));
        
        string IMigrationMetadata.Id
        {
            get { return "201608181643122_V00"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
